server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:tcp://localhost/~/test #jdbc:h2:file:~/h2/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  logging:
    level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true